// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKnnYROBXzhPBppnW8zCfCb22UsFIUCWE',
    appId: '1:22541716063:web:fc4712766fd0f7a0c029ea',
    messagingSenderId: '22541716063',
    projectId: 'letmebeyourchefflutter',
    authDomain: 'letmebeyourchefflutter.firebaseapp.com',
    storageBucket: 'letmebeyourchefflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JDa3unzPAcKAJPH7KwPr-MO1IaQtJj4',
    appId: '1:22541716063:android:53c5906de4e1df8bc029ea',
    messagingSenderId: '22541716063',
    projectId: 'letmebeyourchefflutter',
    storageBucket: 'letmebeyourchefflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIvOCUY2yU4yaAveD89kJDn_LDwFMZiFs',
    appId: '1:22541716063:ios:a1c36da9692017a2c029ea',
    messagingSenderId: '22541716063',
    projectId: 'letmebeyourchefflutter',
    storageBucket: 'letmebeyourchefflutter.appspot.com',
    iosBundleId: 'com.example.letmebeyourchefflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIvOCUY2yU4yaAveD89kJDn_LDwFMZiFs',
    appId: '1:22541716063:ios:4d262d584725c471c029ea',
    messagingSenderId: '22541716063',
    projectId: 'letmebeyourchefflutter',
    storageBucket: 'letmebeyourchefflutter.appspot.com',
    iosBundleId: 'com.example.letmebeyourchefflutter.RunnerTests',
  );
}
